Collections:
- Metadata:
    Architecture:
    - EG3D
  Name: EG3D
  Paper:
  - https://openaccess.thecvf.com/content/CVPR2022/html/Chan_Efficient_Geometry-Aware_3D_Generative_Adversarial_Networks_CVPR_2022_paper.html
  README: configs/eg3d/README.md
Models:
- Config: configs/eg3d/eg3d_shapenet.py
  In Collection: EG3D
  Metadata:
    Training Data: Others
  Name: eg3d_shapenet
  Results:
  - Dataset: Others
    Metrics:
      FID50k: 5.6573
      FID50k-Camera: 5.2325
    Task: 3D-aware Generation
  Weights: <>
- Config: configs/eg3d/eg3d_afhq.py
  In Collection: EG3D
  Metadata:
    Training Data: Others
  Name: eg3d_afhq
  Results:
  - Dataset: Others
    Metrics:
      FID50k: 2.9134
      FID50k-Camera: 6.4213
    Task: 3D-aware Generation
  Weights: <>
- Config: configs/eg3d_ffhq.py
  In Collection: EG3D
  Metadata:
    Training Data: FFHQ
  Name: eg3d_ffhq
  Results:
  - Dataset: FFHQ
    Metrics:
      FID50k: 4.3076
      FID50k-Camera: 6.4453
    Task: 3D-aware Generation
  Weights: <>
